name: Pages

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}


    - name: Install dependencies
      run: |
        npm install
        npm install react-bootstrap bootstrap
      
    - name: Create env file
      run: |
        ls
        touch .env
        echo REACT_APP_TEST=1234asd >> .env
        cat .env
        echo "env created successfully"
        ls

    - name: Build
      run: npm run build
      env:
          API_KEY: ${{ secrets.PAGES7 }}
        
    - name: Deploy
      run: |
         git config --global user.name "${{ runner.name }}"
         git config --global user.email $user_email
         git remote set-url origin https://${{ secrets.PAGES7 }}@github.com/${repository}
         npm run deploy
      env:
#         user_name: 'github-actionsPages'
         user_email: 'github-actionsPages@users.noreply.github.com'
#         github_token: ${{ secrets.PAGESTOKEN }}
         repository: ${{ github.repository }}
